name: frontend_mobile_app_flutter
description: "version 0.1.2.0"

publish_to: "none"

#android & ios
version: 0.1.2+2

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.7
  image_picker: ^0.8.7+5
  shared_preferences: ^2.2.2
  http: ^0.13.6
  get_it: ^7.6.4
  injectable: ^2.1.5
  cached_network_image: ^3.2.3
  logger: ^1.0.0
  fluttertoast: ^8.0.8
  camera: ^0.11.1
  flutter_launcher_icons: ^0.14.3
  path_provider: ^2.1.5
  intl: ^0.18.0
  google_maps_flutter: ^2.2.0
  geolocator: ^9.0.2
  google_places_flutter: ^2.0.9
  connectivity_plus: ^6.1.3
  lottie: ^2.7.0
  url_launcher: ^6.3.1
  share_plus: ^7.2.2
  app_links: ^3.5.1
  font_awesome_flutter: ^10.6.0
  video_player: ^2.7.2
  flutter_image_compress: ^2.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/logo_app_influyo.svg"
  adaptive_icon_foreground: "assets/icons/logo_app_influyo.svg"
  adaptive_icon_background: "#ffffff"

flutter:
  uses-material-design: true

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Black.ttf
          weight: 900

  assets:
    - assets/images/influyo_logo.png
    - assets/images/noSearchResults.png
    - assets/images/review.gif
    - assets/images/check.gif
    - assets/images/delete.png
    - assets/icons/logo_app_influyo.svg
    - assets/icons/filtericon.svg
    - assets/icons/exploraicon.svg
    - assets/icons/calendarioicon.svg
    - assets/icons/eventosicon.svg
    - assets/icons/chaticon.svg
    - assets/icons/perfilicon.svg
    - assets/icons/notificationsicon.svg
    - assets/icons/closeicon.svg
    - assets/icons/revisionicon.svg
    - assets/icons/revisionicon.svg
    - assets/icons/cameraoutlineicon.svg
    - assets/icons/camerafillicon.svg
    - assets/icons/facebookicon.svg
    - assets/icons/instagramicon.svg
    - assets/icons/tiktokicon.svg
    - assets/icons/facebookicon.svg
    - assets/icons/instagramicon.svg
    - assets/icons/tiktokicon.svg
    - assets/icons/facebookicon.png
    - assets/icons/instagramicon.png
    - assets/icons/tiktokicon.png
    - assets/icons/youtubeicon.png
    - assets/icons/twitchicon.png
